import type { AuthoringProfile } from "../AuthoringProfile";

export const englishProfile: AuthoringProfile = {
  id: "en",
  direction: "ltr",
  detectionKeys: [
    "name",
    "header",
    "personalInfo",
    "summary",
    "skills",
    "experience",
    "education",
  ],
  aliases: {
    locale: ["locale", "language", "lang"],
    meta: ["meta", "metadata"],

    personalContainer: ["personalInfo", "header", "profile", "personal-info"],
    name: ["name", "fullName"],
    titles: ["titles", "roles", "headlines"],
    location: ["location", "city"],
    country: ["country", "nation"],
    phone: ["phone", "mobile", "contact"],
    email: ["email", "mail"],
    photo: ["photo", "avatar", "image"],
    social: ["social", "socials", "links"],

    summary: ["summary", "about", "profileSummary"],
    skills: ["skills"],
    experience: ["experience", "experiences", "workExperience"],
    education: ["education", "educations", "academics"],
    awards: ["awards", "recognitions"],
    additional: ["additional", "additionalInfo", "extra", "misc"],
    projects: ["projects"],
    certifications: ["certifications", "certification"],
    interests: ["interests"],

    category: ["category", "label"],
    items: ["items", "values", "skills", "techs"],
    company: ["company", "organization"],
    position: ["position", "role", "title"],
    duration: ["duration"],
    highlights: ["highlights", "achievements"],
    techs: ["techs", "technologies", "stacks"],
    institution: ["institution", "university", "school"],
    degree: ["degree"],
    field: ["field", "specialization", "major"],
    courses: ["courses", "coursework"],
    title: ["title", "name"],
    issuer: ["issuer", "organization", "awardedBy"],
    year: ["year", "date"],
    detail: ["detail", "description", "summary"],
    logo: ["logo", "icon", "badge"],
    githubRepo: ["githubRepo", "github", "repository", "repo"],
    snapshot: ["snapshot", "image", "thumbnail"],
    onlineLink: ["onlineLink", "link", "url", "certificateUrl"],
    label: ["label", "title", "name"],
    value: ["value", "value1", "text"],
    from: ["from", "start", "startYear"],
    to: ["to", "end", "endYear"],
  },
  socialPlatforms: {
    linkedin: ["linkedin", "linkedIn"],
    github: ["github", "gitHub"],
    twitter: ["twitter", "x"],
    youtube: ["youtube"],
    website: ["website", "portfolio", "site"],
  },
  captions: {
    personal: { name: "Home", title: "Home" },
    summary: { name: "About", title: "About Me" },
    skills: { name: "Skills", title: "Skills" },
    experience: { name: "Experience", title: "Experience" },
    education: { name: "Education", title: "Education" },
    awards: { name: "Awards", title: "Awards & Recognition" },
    additional: { name: "Additional", title: "Additional Info" },
    projects: { name: "Projects", title: "Projects" },
    certifications: { name: "Certifications", title: "Certifications" },
    interests: { name: "Interests", title: "Interests" },
  },
  durationDelimiters: ["--", "—", "–", " to ", " - "],
};
