import type { AuthoringProfile } from '../AuthoringProfile';

export const urduProfile: AuthoringProfile = {
  id: 'ur',
  direction: 'rtl',
  detectionKeys: ['نام', 'سرورق', 'خلاصہ', 'مہارتیں', 'تجربہ', 'تعلیم', 'ایوارڈز'],
  aliases: {
    locale: ['لوکیل', 'زبان', 'locale', 'language'],
    meta: ['میٹا', 'meta', 'metadata'],

    personalContainer: ['سرورق', 'ذاتی معلومات', 'پرسنل انفو', 'personalInfo'],
    name: ['نام', 'پورا نام', 'name'],
    titles: ['عہدے', 'عنوانات', 'titles'],
    location: ['مقام', 'شہر', 'location'],
    country: ['ملک', 'country'],
    phone: ['فون', 'موبائل', 'phone'],
    email: ['ای میل', 'ایمیل', 'email'],
    photo: ['تصویر', 'فوٹو', 'photo'],
    social: ['سوشل', 'روابط', 'social'],

    summary: ['خلاصہ', 'تعارف', 'summary'],
    skills: ['مہارتیں', 'صلاحیتیں', 'skills'],
    experience: ['تجربہ', 'تجربات', 'experience'],
    education: ['تعلیم', 'education'],
    awards: ['ایوارڈز', 'اعزازات', 'awards'],
    additional: ['اضافی', 'دیگر', 'additional'],
    projects: ['منصوبے', 'پروجیکٹس', 'projects'],
    certifications: ['سرٹیفیکیشنز', 'اسناد', 'certifications'],
    interests: ['دلچسپیاں', 'مشاغل', 'interests'],

    category: ['زمرہ', 'قسم', 'category'],
    items: ['اشیاء', 'آئٹمز', 'items'],
    company: ['کمپنی', 'company'],
    position: ['عہدہ', 'پوزیشن', 'position'],
    duration: ['دورانیہ', 'duration'],
    highlights: ['نمایاں کام', 'اہم نکات', 'highlights'],
    techs: ['ٹیکنالوجیز', 'ٹیک', 'techs'],
    institution: ['ادارہ', 'یونیورسٹی', 'institution'],
    degree: ['ڈگری', 'degree'],
    field: ['شعبہ', 'فیلڈ', 'field'],
    courses: ['کورسز', 'مضامین', 'courses'],
    title: ['عنوان', 'title'],
    issuer: ['جاری کنندہ', 'issuer'],
    year: ['سال', 'year'],
    detail: ['تفصیل', 'خلاصہ', 'detail'],
    logo: ['لوگو', 'نشان', 'logo'],
    githubRepo: ['گٹ ہب ریپو', 'ریپوزٹری', 'githubRepo', 'repo'],
    snapshot: ['سنیپ شاٹ', 'تصویر', 'snapshot'],
    onlineLink: ['آن لائن لنک', 'لنک', 'onlineLink', 'url'],
    label: ['لیبل', 'عنوان', 'label'],
    value: ['قدر', 'value', 'value1'],
    from: ['سے', 'from', 'آغاز'],
    to: ['تک', 'to', 'اختتام'],
  },
  socialPlatforms: {
    linkedin: ['لنکڈ ان', 'لنکڈان', 'linkedin'],
    github: ['گٹ ہب', 'github'],
    twitter: ['ٹویٹر', 'twitter', 'twiiter'],
    youtube: ['یوٹیوب', 'youtube'],
    website: ['ویب سائٹ', 'سائٹ', 'website'],
  },
  captions: {
    personal: { name: 'سرورق', title: 'سرورق' },
    summary: { name: 'تعارف', title: 'میرے بارے میں' },
    skills: { name: 'مہارتیں', title: 'مہارتیں' },
    experience: { name: 'تجربہ', title: 'تجربہ' },
    education: { name: 'تعلیم', title: 'تعلیم' },
    awards: { name: 'ایوارڈز', title: 'ایوارڈز' },
    additional: { name: 'اضافی', title: 'اضافی معلومات' },
    projects: { name: 'منصوبے', title: 'منصوبے' },
    certifications: { name: 'سرٹیفیکیشنز', title: 'سرٹیفیکیشنز' },
    interests: { name: 'دلچسپیاں', title: 'دلچسپیاں' },
  },
  durationDelimiters: ['--', '—', '–', ' تا ', ' - '],
};
